from __future__ import annotations

import json
from pathlib import Path
from typing import Iterable

from .models import Shot, ShotAnalysis, ViewerState, format_timestamp


SYSTEM_ANALYSIS_GOAL = """You are analyzing a short film shot by shot for editing, cinematography, sound, and narrative craft.
Work in chronological order. Use the viewer_state as memory from prior shots.
Track recurring characters, locations, motifs, unresolved questions, and what the audience learns.
For each shot, produce visual description, audio/dialogue, action/camera, narrative function, notes, and an updated viewer_state."""


class StubAnalyzer:
    """Placeholder analyzer that preserves the interface for a real LLM adapter."""

    def __init__(self) -> None:
        self.viewer_state = ViewerState(
            story_summary="No model analysis has been run yet.",
            open_questions=["Replace the stub analyzer with a vision/audio LLM pass."],
        )

    def analyze(self, shot: Shot) -> ShotAnalysis:
        start = format_timestamp(shot.start)
        end = format_timestamp(shot.end)
        duration = f"{shot.duration:.2f}s"
        return ShotAnalysis(
            shot_title=f"Shot {shot.number}",
            visual_description=(
                "LLM visual analysis pending. Representative frame captured for this shot."
            ),
            audio_dialogue=(
                "Audio transcription pending. Future pass should align dialogue, voiceover, "
                "music, and sound effects to this shot interval."
            ),
            action_camera=(
                f"Shot interval {start} to {end} ({duration}). Camera movement and primary/secondary "
                "actions should be filled by the model pass."
            ),
            narrative_function=(
                "Narrative analysis pending. The model pass should describe what new story "
                "information, tension, reveal, or emotional turn this shot contributes."
            ),
            notes=(
                "Generated by the scaffold analyzer; timing and screenshot are real, prose fields "
                "are placeholders."
            ),
        )

    def packet_for(self, shot: Shot) -> dict[str, object]:
        return {
            "system_goal": SYSTEM_ANALYSIS_GOAL,
            "viewer_state": self.viewer_state.as_dict(),
            "shot": {
                "number": shot.number,
                "start": format_timestamp(shot.start),
                "end": format_timestamp(shot.end),
                "duration_seconds": round(shot.duration, 3),
                "screenshot_path": str(shot.screenshot_path) if shot.screenshot_path else None,
                "scene_score": shot.scene_score,
            },
            "requested_output": {
                "visual_description": "Shot type, framing, characters, location, lighting, color, composition.",
                "audio_dialogue": "Dialogue, voiceover, music, sound design, notable silence.",
                "action_camera": "Primary action, secondary actions, blocking, camera movement.",
                "narrative_function": "What the viewer learns; story beat; setup/payoff; emotional turn.",
                "updated_viewer_state": "Compact memory for the next shot.",
            },
        }


def analyze_shots(shots: Iterable[Shot], packets_path: Path) -> dict[int, ShotAnalysis]:
    analyzer = StubAnalyzer()
    analyses: dict[int, ShotAnalysis] = {}
    packets_path.parent.mkdir(parents=True, exist_ok=True)

    with packets_path.open("w", encoding="utf-8") as handle:
        for shot in shots:
            analyses[shot.number] = analyzer.analyze(shot)
            handle.write(json.dumps(analyzer.packet_for(shot), ensure_ascii=False) + "\n")

    return analyses
